// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYO6p9dJ6aejWnm3-9JiEWX9vUJHtaV7I',
    appId: '1:564788876761:web:21dec7619a2aeedeb6f5c8',
    messagingSenderId: '564788876761',
    projectId: 'healthxchangehack',
    authDomain: 'healthxchangehack.firebaseapp.com',
    storageBucket: 'healthxchangehack.appspot.com',
    measurementId: 'G-YKQ6HFZRS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMcVPAbeU2yINIwgt6pvuSDWArp-YSzZU',
    appId: '1:564788876761:android:35a18cacba74910db6f5c8',
    messagingSenderId: '564788876761',
    projectId: 'healthxchangehack',
    storageBucket: 'healthxchangehack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNEdfKzLgXrmnH9rv3zu18amjWYxwgtcQ',
    appId: '1:564788876761:ios:a3109b2f3e1ed5eeb6f5c8',
    messagingSenderId: '564788876761',
    projectId: 'healthxchangehack',
    storageBucket: 'healthxchangehack.appspot.com',
    iosClientId: '564788876761-h8o8g79p72n7udupf7fkai1aaagp6l1a.apps.googleusercontent.com',
    iosBundleId: 'com.healthxchange.HealthXchange',
  );
}
